spring:
  datasource:
    url: jdbc:postgresql://db:5432/f1predictor
    username: f1user
    password: f1pass
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


